eslint/tsc-meetings

notes/2019/2019-06-06.md

Teddy wasn't present, and I was present but am not on the list. :smile:

Docs: Update meeting participants

---

notes/2019/2019-06-20.md

Seems we forgot to take notes for the last meeting. Backfilling them with this PR.

Add 2019-06-20 meeting notes (closes #135)

---

.github/workflows/ci.yml

ci: Run only on main branch

---

notes/2022/2022-07-28.md

docs: Add 2022-07-28 meeting notes

---

notes/2022/2022-08-11.md

docs: Add 2022-08-11 meeting notes

---

notes/2022/2022-08-25.md

docs: Add 2022-08-25 meeting notes

---

notes/2022/2022-09-22.md

docs: Add 2022-09-22 meeting notes

---

notes/2022/2022-10-06.md

docs: Add 2022-10-06 meeting notes

---

notes/2022/2022-11-03.md

docs: Add 2022-11-03 meeting notes

---

notes/2022/2022-11-17.md

docs: Add 2022-11-17 meeting notes

---

notes/2022/2022-12-01.md

docs: Add 2022-12-01 meeting notes

---

notes/2022/2022-12-29.md

docs: Add 2022-12-29 meeting notes

---

notes/2023/2023-01-12.md

docs: Add 2023-01-12 meeting notes

---

notes/2023/2023-01-26.md

docs: Add 2023-01-16 meeting notes

---

notes/2023/2023-02-09.md

docs: Add 2023-02-09 meeting notes

---

notes/2023/2023-02-23.md

docs: Add 2023-02-23 meeting notes

---

notes/2023/2023-03-09.md

docs: Add 2023-03-09 meeting notes

---

notes/2023/2023-04-06.md

Closes https://github.com/eslint/tsc-meetings/issues/420

docs: Add 2023-04-06 meeting notes

---

notes/2023/2023-04-20.md

Closes https://github.com/eslint/tsc-meetings/issues/424

docs: Add 2023-04-20 meeting notes

---

notes/2023/2023-06-01.md

Closes https://github.com/eslint/tsc-meetings/issues/432

docs: Add 2023-06-01 meeting notes

---

notes/2023/2023-09-07.md

docs: Add 2023-09-07 meeting notes

---

notes/2023/2023-10-05.md

docs: Add 2023-10-05 meeting notes

---

notes/2023/2023-11-16.md

docs: Add 2023-11-16 meeting notes

---

notes/2023/2023-12-14.md

docs: Add 2023-12-14 meeting notes

---

notes/2024/2024-03-21.md

docs: Add 2024-03-21 meeting notes

---

notes/2024/2024-05-30.md

docs: Add 2024-05-30 meeting notes

---

notes/2024/2024-06-27.md

docs: Add 2024-06-27 meeting notes

---

notes/2024/2024-07-11.md

docs: Add 2024-07-11 meeting notes

---

notes/2025/2025-02-20.md

docs: Add 2025-02-20 meeting notes

---

notes/2025/2025-03-06.md

docs: Add 2025-03-06 meeting notes

---

notes/2025/2025-04-03.md

docs: Add 2025-04-03 meeting notes

---

notes/2025/2025-04-17.md

docs: Add 2025-04-17 meeting notes

---

notes/2025/2025-05-01.md

docs: Add 2025-05-01 meeting notes

---

notes/2025/2025-05-15.md

docs: Add 2025-05-15 meeting notes

---

notes/2025/2025-06-26.md

docs: Add 2025-06-26 meeting notes

---

notes/2025/2025-07-24.md

Added notes for last TSC meeting
These are the meeting notes for TSC 2025-07-24
Closes #601 
The only issue I could not leave a comment on was https://github.com/eslint/rewrite/issues/66

docs: Add 2025-07-24 meeting notes

---

notes/2025/2025-09-04.md

Submit meeting notes for September 4th, 2025
Summarize notes.
Closes #613

docs: Add 2025-09-04 meeting notes

---

notes/2025/2025-09-18.md

Add meeting notes
Adding notes for 2025-09-18 TSC meeting
Fixes #617

docs: Add 2025-09-18 meeting notes
