eslint/tsc-meetings

README.md
Only question I have is if I should explicitly say something like "we prefer that agenda items should be represented as issues with tsc agenda label".
Let me know if anything else needs to be changed.
=> Docs: Emphasize "tsc agenda" label as preferred agenda intake in README

notes/2016/2016-10-13.md
=> Add 2016-10-13 meeting notes

notes/2020/2020-05-21-transcript.md, transcripts/5-21-2020.md
Rather than dealing with setting up a .NET environment and using https://github.com/Tyrrrz/DiscordChatExporter, I threw together a quick little script to generate this (you can see the code [here](https://github.com/kaicataldo/discord-transcript-generator)) that we can use going forward. It's written in Node, so should be easy enough for anyone on the TSC to run it. If we want to add this as an `npm` script in this repo, I can definitely do that (either publishing it or just inlining it), or folks can just clone the repo and run it locally as well.
It will require that the person running the script has access to the shared secrets for Discord API, so we would have to figure out how we want to do that. It would be great if whoever is taking notes can generate the transcript as part of the …
=> Add 5-21-2020 meeting transcript

.eslintignore, .eslintrc.js, .github/workflows/ci.yml, .github/workflows/generate-transcript.yml, .gitignore, package-lock.json, package.json, scripts/generate-transcript.js
Hopefully this works! GitHub Action development always feels like trial and error to me...
=> Chore: automate generation of meeting transcripts

notes/2020/2020-07-02.md
🚧 this does not yet include the transcript. @kaicataldo - let me know how your automation for that is coming along and whether I should run it manually and attach to this PR.
@kaicataldo I structured the notes for the config cloning discussion so that copying the blockquoted parts should give you a decent start on tomorrow's release announcement with links included assuming everyone's happy with the notes.
=> Add 2020-07-02 meeting notes (closes #184)

notes/2020/2020-07-16-transcript.md, package-lock.json, package.json
Took a couple minutes to update the transcript generator package to now include reactions. I was able to update the last meeting, but trying to run it for earlier meetings is resulting in blank transcripts. It might be that Discord's API only allows for messages to be pulled up to a certain date. I did a little googling and wasn't able to find anything, but I'll dig a bit deeper and see if I can see why it's not working. It does seem to be working generally, though (as demonstrated by running the script for the last meeting).
=> Chore: add reactions to transcripts

package-lock.json, package.json
Noticed a [little bug](https://github.com/eslint/tsc-meetings/pull/203/commits/006e55e44c7c1eafa5c090ccb0abb3d1649f05dd) in the formatting of multiple reactions. Updated it manually for this week's transcript but am bumping the version here for next time.
=> Upgrade: discord-transcript-generator@1.1.1

.github/workflows/generate-transcript.yml
The `::set-env` command was [deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) due to a security vulnerability and replaced with [environment files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files). This caused transcript generation for the 2020-11-19 meeting [to fail](https://github.com/eslint/tsc-meetings/actions/runs/380143250).
There's not a great way to test this prior to merging it, so there's a bit of YOLOing going on here. Once this is approved, I'll merge then reopen and close #219 to trigger the workflow. 🤞
=> Chore: Remove deprecated set-env from transcript workflow

.github/workflows/generate-transcript.yml
The fix in #223 allowed the last action run to successfully create #224, but it [failed](https://github.com/eslint/tsc-meetings/runs/1465153998?check_suite_focus=true) before the job completed due to an old version of the Create Pull Request action still using `::set-env`.
[Release v3.4.1](https://github.com/peter-evans/create-pull-request/releases/tag/v3.4.1) removed the deprecated `::set-env` command. We shouldn't be affected by any breaking changes in the [v3 release](https://github.com/peter-evans/create-pull-request/releases/tag/v3.0.0).
=> Upgrade: Create Pull Request action to fix set-env error

README.md
Since meetings have moved from Gitter to Discord, this PR replaces the Gitter link and badge with a link to the Discord server.
shields.io has a Discord badge you could use as well, but it looks like it would need a Discord server admin to set it up:
https://shields.io/category/chat
=> chore: Replace Gitter link with Discord link

.github/workflows/ci.yml, .github/workflows/generate-transcript.yml
Update the `setup-node` action to `v2` for CI node workflows.
https://github.com/marketplace/actions/setup-node-js-environment
=> chore: use `setup-node@v2` in CI

.github/workflows/ci.yml
Refs: #309
This currently includes both `main` and `master`. After I use GitHub's branch rename feature to rename the default branch to `main`, I'll open a follow-up PR that removes `master`.
=> ci: Run on main branch

scripts/generate-transcript.js
Refs: #309
I could've referenced the branch name direction instead with https://github.com/eslint/eslint-github-bot/blob/main/src/plugins/recurring-issues/index.js#L235, but I went with the commit sha to keep the line number consistent.
=> chore: Update outdated link in comment

package-lock.json, package.json
`eslint-config-eslint@6.0.0` has a peer dependency on `eslint-plugin-jsdoc@^15.9.5`, whereas `package.json` has a `devDependency` on `eslint-plugin-jsdoc@^28.6.1`. Those ranges are in conflict.
This change upgrades to `eslint-config-eslint@7.0.0`, which changes the peer dependency to `eslint-plugin-jsdoc@>=22.1.0`, resolving the conflict.
This should fix the CI failures seen in #355 and #356. This peer dependency version range conflict was previously being ignored, but a behavior change in npm 8.6.0 started reporting it. Whether that's a backwards-incompatible change in a semver-minor version is left as a question for the reader.
=> ci: Upgrade eslint-config-eslint to fix peer conflict

notes/2023/2023-03-23.md
Closes: https://github.com/eslint/tsc-meetings/issues/417
=> docs: Add 2023-03-23 meeting notes

notes/2023/2023-06-29.md
Closes https://github.com/eslint/tsc-meetings/issues/437
=> docs: Add 2023-06-29 meeting notes

.github/workflows/generate-transcript.yml, package.json
Refers https://github.com/eslint/eslint/issues/14827
This updates the names of the scripts in package.json to be consistent with the [new standard](https://eslint.org/docs/latest/contribute/package-json-conventions).
=> chore: standardize npm script names

notes/2023/2023-09-21.md
=> docs: Add 2023-09-21 meeting notes

notes/2023/2023-12-28.md
=> docs: Add 2023-12-28 meeting notes

notes/2024/2024-01-25.md
=> docs: Add 2024-01-25 meeting notes

notes/2024/2024-02-08.md
=> docs: Add 2024-02-08 meeting notes

notes/2024/2024-02-22.md
=> docs: Add 2024-02-22 meeting notes

notes/2024/2024-03-07.md
=> docs: Add 2024-03-07 meeting notes

notes/2024/2024-04-04.md
=> docs: Add 2024-04-04 meeting notes

notes/2024/2024-04-18.md
=> docs: Add 2024-04-18 meeting notes

notes/2024/2024-05-02.md
=> docs: Add 2024-05-02 meeting notes

notes/2024/2024-05-16.md
=> docs: Add 2024-05-16 meeting notes

notes/2024/2024-06-13.md
=> docs: Add 2024-06-13 meeting notes

notes/2024/2024-07-25.md
=> docs: Add 2024-07-25 meeting notes

notes/2024/2024-08-08.md
=> docs: Add 2024-08-08 meeting notes

notes/2024/2024-08-22.md
=> docs: Add 2024-08-22 meeting notes

notes/2024/2024-09-05.md
=> docs: Add 2024-09-05 meeting notes

notes/2024/2024-09-19.md
=> docs: Add 2024-09-19 meeting notes

notes/2024/2024-10-03.md
=> docs: Add 2024-10-03 meeting notes

notes/2024/2024-10-17.md
=> docs: Add 2024-10-17 meeting notes

notes/2024/2024-10-31.md
=> docs: Add 2024-10-31 meeting notes

notes/2024/2024-11-14.md
Closes #544 
Note: I've omitted the conversation regarding some last minute PRs we wanted to merged before the deployment as a) it was a bit hard to follow and b) seem unnecessary to the notes. Let me know your thoughts.
=> docs: Add 2024-11-14 meeting notes

notes/2024/2024-11-28.md
=> docs: Add 2024-11-28 meeting notes

notes/2024/2024-12-12.md
=> docs: Add 2024-12-12 meeting notes

notes/2025/2025-01-09.md
=> docs: Add 2025-01-09 meeting notes

notes/2025/2025-01-23.md
=> docs: Add 2025-01-23 meeting notes

notes/2025/2025-02-06.md
=> docs: Add 2025-02-06 meeting notes
